# Generated by Django 5.2.14 on 2026-07-05 04:57

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique identifier')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator(), django.core.validators.MinLengthValidator(5)], verbose_name='Username')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=6, verbose_name='Gender')),
                ('picture', stdimage.models.StdImageField(blank=True, force_min_size=False, max_length=500, null=True, upload_to='users/%Y/%m/%d/', variations={'large': {'height': None, 'width': 1920}, 'medium': {'height': None, 'width': 800}, 'small': {'height': None, 'width': 400}, 'thumbnail': {'crop': True, 'height': 100, 'width': 100}}, verbose_name='Photo')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Unique identifier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and time of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date and time of last update')),
                ('email', models.EmailField(error_messages={'unique': 'This email address is already in use.'}, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='email address')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates whether the email address has been verified.', verbose_name='verified')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'User email',
                'verbose_name_plural': 'User emails',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['email'], name='users_usere_email_56e9d9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_verified', True)), fields=('email',), name='unique_verified_email')],
            },
        ),
    ]
