/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and runtime metadata
         * @description ``GET /api/v1/meta/``: app name, deployed version, environment and languages.
         *
         *     Public on purpose: the SPA calls it first to label the build it is talking to, and
         *     it doubles as the end-to-end example of the API contract flow (DRF view ->
         *     drf-spectacular schema -> api/openapi.yaml -> generated TypeScript types).
         */
        get: operations["api_v1_meta_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description ``GET /healthz/``: liveness probe. No dependencies by design.
         *
         *     At runtime ``common.middleware.HealthCheckMiddleware`` answers this path before the
         *     URL resolver (so probes work with any ``Host`` header); the view documents the
         *     contract and is the fallback if the middleware is removed.
         */
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description ``GET /readyz/``: readiness probe — database and cache reachable, else 503.
         *
         *     Same middleware note as ``HealthzView``.
         */
        get: operations["readyz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ``GET /healthz/`` — liveness. */
        Health: {
            status: components["schemas"]["HealthStateEnum"];
        };
        /**
         * @description * `ok` - ok
         *     * `error` - error
         * @enum {string}
         */
        HealthStateEnum: "ok" | "error";
        Language: {
            code: string;
            name: string;
        };
        /** @description Public build and runtime facts a client needs before it knows anything else. */
        Meta: {
            name: string;
            version: string;
            environment: string;
            languages: components["schemas"]["Language"][];
        };
        /** @description ``GET /readyz/`` — readiness; HTTP 503 when any check is ``error``. */
        Readiness: {
            status: components["schemas"]["HealthStateEnum"];
            checks: components["schemas"]["ReadinessChecks"];
        };
        ReadinessChecks: {
            database: components["schemas"]["HealthStateEnum"];
            cache: components["schemas"]["HealthStateEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_v1_meta_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    readyz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
