"""Stream a gzipped tar of all media objects in the bucket to stdout.

Media lives in S3/MinIO, not on the container filesystem, so it is dumped through
the app rather than by tarring a local directory. Static files (``static/`` prefix)
are excluded — they are regenerated by ``collectstatic`` and need no backup.
Progress goes to stderr so it never corrupts the tar stream on stdout.

    docker compose exec -T backend python manage.py media_dump > media.tar.gz
"""

import io
import sys
import tarfile
import time

from django.core.files.storage import default_storage
from django.core.management.base import BaseCommand

STATIC_PREFIX = "static/"


class Command(BaseCommand):
    help = "Stream a gzipped tar of all media objects to stdout (excludes static/)."

    def add_arguments(self, parser):
        parser.add_argument("--prefix", default="", help="Only dump keys under this prefix.")
        parser.add_argument("--include-static", action="store_true", help="Also dump static/ objects.")

    def handle(self, *args, **options):
        prefix = options["prefix"]
        include_static = options["include_static"]
        bucket = default_storage.bucket
        collection = bucket.objects.filter(Prefix=prefix) if prefix else bucket.objects.all()

        count, total = 0, 0
        with tarfile.open(fileobj=sys.stdout.buffer, mode="w|gz") as tar:
            for obj in collection:
                key = obj.key
                if key.endswith("/"):
                    continue
                if not include_static and key.startswith(STATIC_PREFIX):
                    continue
                data = default_storage.open(key, "rb").read()
                info = tarfile.TarInfo(name=key)
                info.size = len(data)
                info.mtime = int(time.time())
                tar.addfile(info, io.BytesIO(data))
                count += 1
                total += len(data)
                if count % 250 == 0:
                    self.stderr.write(f"  …{count} objects ({total / 1024 / 1024:.0f} MB)")

        self.stderr.write(self.style.SUCCESS(f"Dumped {count} objects, {total / 1024 / 1024:.1f} MB"))
